### ISSUE TITLE
Zrušit přebliknutí do běla při zoomování 

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#1]
Když zoomuju obrázek a (předpokládám) přejdu na jiný zoom level, tak se obrazovka smaže do bíla a znova vykreslí nové dlaždice. To způsobuje nepříjemné bliknutí. Totéž když posouvám zazoomovaný obrázek - pokud není natažená dlaždice z daného zoom levelu, je tam bílý podklad. Měly by tam být provizorně dlaždice z vyššího zoomlevelu.

**Comment by zabak** [comment]
Ještě doplním - teď se to chová tak, že při zoomování tam problikávají dlaždice z jiných částí obrázku na místech kde vůbec nemají co dělat.

**Comment by Fiser33** [comment]
Vykreslovani pozadi bylo ve verzi 1.0 (4) vylepseno. Nyni by nemelo byt bile pozadi viditelne nikde. Taktez bylo odstraneno problikavani nespravnych dlazdic. 

Pozadi nyni vyuziva nekterych jiz stazenych dlazdic obrazku, coz by pri zoomu melo snizit "pixelovatost" pozadi. Prosim o potvrzeni, pripadne dalsi komentare.

**Comment by zabak** [comment]
Vyřešeno, další případné připomínky napíšu do nového issue.
