### ISSUE TITLE
Prohlizeni na iPadu Pro

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/iOSTiledViewer#10]
Na iPadu Pro 12.7 inch prohlizecka pada. 
Fatal error - Index out of range ....
https://www.dropbox.com/s/xf60xl7vah7v3q1/Screenshot%202017-01-21%2009.43.55.png?dl=0
Vsechna ostatni zarizeni, ktera jsem zkousek jsou v pohode. Jediny problem je v ipadu pro 12.7.

**Comment by Fiser33** [comment]
Diky, mrknu se na to jak nejdriv to jen pujde.

**Comment by Fiser33** [comment]
Melo by byt opraveno v testovaci aplikaci verze 1.0 (6), coz odpovida verzi 0.2.2 knihovny. Prosim o kontrolu.
