### ISSUE TITLE
IIIF Presenter zobrazuje šedou verzi obrázku z IIPImage serveru přes IIIF

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#12]
V testovací aplikaci je default zobrazení map z imageserveru v odstínech šedi. Možná to souvisí s verzí manifestu - IIPImage Server generuje kvality dle IIIF presentation api v. 1 kde se používá mj. kvalita "native" zatímco ve verzi 2 se přešlo na "default"

**Comment by Fiser33** [comment]
U mne je zobrazeni barev u nove vlozenych IIIF obrazu v poradku (viz screenshoty).

gray:
![map_gray](https://cloud.githubusercontent.com/assets/2512325/22260026/e448ca30-e267-11e6-9b2c-3303c2d6921b.png)
native:
![map_native](https://cloud.githubusercontent.com/assets/2512325/22260027/e44b7bae-e267-11e6-8be7-0bdda9150ae4.png)

Co se tyce verze IIIF protokolu, metadata k obrazum jsou psany podle verze 2, tudiz by nemely obsahovat kvalitu "native".

**Comment by zabak** [comment]
To byla připomínka k aplikaci, že ta vezme a zobrazí jen verzi gray a jiné kvality není možno v ní zobrazit. Nebo to nějak jde?

**Comment by Fiser33** [comment]
Omlouvam se, myslel jsem, ze se jedna spise o bug.

V testovaci aplikaci momentalne neni mozne menit kvalitu obrazu. Jiz jsem nad tim ale dnes premyslel a planuji pridat nejakou jednoduchou obrazovku s nastavenim pro kvalitu a format.

**Comment by zabak** [comment]
Možná pro začátek by stačilo zobrazit default kvalitu (i když mít možnost vidět i ty ostatní má smysl) - podle čeho se vlastně aplikace rozhodne, kterou zobrazí? Očekával bych default.

**Comment by Fiser33** [comment]
Aktualne aplikace pouziva prvni uvedenou kvalitu. Pokud nejsou uvedeny kvality zadne, tak pouzije "default".

**Comment by zabak** [comment]
Aha, ale první uvedená kvalita je ta v http://iiif.io/api/image/2/level1.json, tedy "default". A ta by měla být vyžadována - resp. druhá možnost je pak pokud jsou nabízeny další kvality tak nabídnout ty další. Ale pořád by mělo platit že pokud je k dispozici color, tak má přednost před gray a bitonal. viz taky http://iiif.io/api/image/2.1/compliance/#quality 
Tím native se ještě budu zabývat, zjistím proč to tam je - ale obecně by to mělo být tak, že je to ve verzi 1 protokolu totéž co default ve verzi 2.

**Comment by Fiser33** [comment]
V testovaci aplikaci verze 1.0 (6) byla pridana obrazovka pro nastaveni kvality a formatu obrazu. Parametry lze menit jen u IIIF obrazu a to v pripade, kdy je na vyber vice nez jedna moznost. Toto issue timto zaviram.
