### ISSUE TITLE
nefunguje kvalita gray z iimpimage serveru

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#14]
Pokud vyberu kvalitu gray z image serveru iipimage (např obě mapy) tak mi to zahlásí Error docoding image

**Comment by Fiser33** [comment]
Problem je v pochopeni IIIF protokolu. Ma knihovna zasila na server pozadavek o urcitou dlazdici, kdy jako zadanou velikost obrazku posila velikost dlazdice na displeji. Server ovsem na takovy pozadavek nekdy vraci nevalidni data. Pokud uvedu definovanou velikost (v souboru info.json, atribut sizes), tak server vraci validni obrazek, ktery ale bude v dlazdici ve vysledku stejne roztazeny na velikost dlazdice.

Nevalidni pozadavek (mimochodem funguje pro kvalitu default): http://imageserver.mzk.cz/mzk03/000/903/918/2619267604/0,0,1024,1024/256,/0/gray.jpg
Validni pozadavek: http://imageserver.mzk.cz/mzk03/000/903/918/2619267604/0,0,1024,1024/270,222/0/gray.jpg

Dle IIIF specifikace by mela byt definovana velikost pouzita pouze v pripade, kdy zadam o cely obrazek, ne o konkretni region, viz:
> The objects in the sizes list have the properties in the following table. Images requested using these sizes should have a region parameter of “full” and rotation of “0”. The size should be requested using the canonical syntax of w,. Thus, the full URL for an image with “default” quality in “jpg” format would be: {scheme}://{server}/{prefix}/{identifier}/full/{width},/0/default.jpg

Pokud je oprava na serveru komplikovana, muzu i pri pozadavcich na region zadat o definovanou velikost. To muze ale vest k pomalejsimu vykreslovani, jelikoz odpoved pro kazdou dlazdici bude o neco vetsi.

**Comment by dsecik** [comment]
Tato chyba sa prejavuje v najnovsej verzii IIPImage. Nasadil som preto predchadzajucu verziu ktora pre vyssie uvedeny poziadavok vrati validny obrazok. Mozete prosim otestovat?

**Comment by Fiser33** [comment]
Funguje. V testovaci aplikaci jsem jiz na tento problem nenarazil.

**Comment by zabak** [comment]
@dsecik nahlásíš tu chybu Ruvenovi?

**Comment by dsecik** [comment]
@zabak  vcera som napisal issue ruven/iipsrv#87 Mame tam este otvorenu ruven/iipsrv#86 ak to nesposobuje problem ani v tej klokanovej prohlizecce tak by sme to mohli zavriet kedze neexistuje specka ako to ma vyzerat, co myslis?

**Comment by dsecik** [comment]
Uz je to opravene  ruven/iipsrv#90
