### ISSUE TITLE
Padá to na přidaném obrázku

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#2]
Přidal jsem do test.json jeden link na obrázek. V Miradoru to funguje, ale IIIF Presenter na tom padne. Jde o http://sanddragon.bl.uk/IIIFImageService/cotton_ms_clab4_f004r/info.json

**Comment by Fiser33** [comment]
Odkazovany obrazek je dostupny pouze pres API verze 1.1. Knihovna aktualne podporuje verze 2.0 a 2.1.

Problem lze resit:
a) implementace zpetne podpory i verze 1.1
b) ohlasenim chyby pri nepodporovane verzi

**Comment by zabak** [comment]
Změny mezi 1.1 a 2.0 jsou popsány zde: http://iiif.io/api/image/2.0/change-log/#added-tiles-property-to-image-information-document

Nevím samozřejmě na čem to padá, ale pokud je to jen nějaká drobnost bylo by lepší doplnit i podporu pro 1.1.  Přistupoval bych k tomu ale pragmaticky, tj. cílem u verze 1.1 je zobrazit obrázek a zoomovat v něm. Nebo je tam nějaký zásadní problém, proč by to bylo příliš pracné? Ať už bude rozhodnutí jakékoli, v textu práce je bude třeba uvést a obhájit.

**Comment by zabak** [comment]
vyřešeno
