### ISSUE TITLE
rozdílná barevnost na různých tabletech

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#3]
Když vedle sebe položím ipad retina a ipad mini, tak každý má viditelně jinou barevnost. Dá se toto nějak sjednotit?

**Comment by ovyhlidal** [comment]
Tohle jsme kdysi zkouseli, kdyz jsme vedle sebe dali 5 iphonu 4s, bohuzel z tech 5 kazdy mel barvy posunute do jineho odstinu/teploty. Jeden mel vylozene zlute teple barvy a dalsi mel naopak vylozene modre tony... Pokud se jedna o podobny problem, tak bohuzel. Je to problem Applu a jeho vyrobnich processu. 
Ted jsme zkusili vedle sebe dat 2 iphony 6s a bohuzel i tady byli videt stejne problemy...
