### ISSUE TITLE
extrémní zoom 

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#4]
u obrázku ze sanddragon.bl.uk když zazoomuju na maximum (tj když je cca jedno písmeno na obrazovku, tak překročím nějakou hranici a obrazovka zůstane bílá. Prohlížečka by měla mít nějaký interní limit (max. zoom) a přes něj nejít. Podobně se chová mapa Moravy. Ta se dá zvětšit jen do určité míry a dál ne.

**Comment by Fiser33** [comment]
Opraveno ve verzi 1.0 (4). Prosim o potvrzeni.

**Comment by zabak** [comment]
ano, opraveno.
