### ISSUE TITLE
aplikace nejede ve fullscreenu

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#5]
Tohle je drobnost, ale je nějaký důvod, proč aplikace nezobrazuje obrázek přes celou obrazovku?

**Comment by Fiser33** [comment]
Čtečka zobrazí obrázek v největší možné velikost tak, aby byl celý viditelný v rámci čtečky. V testovací aplikaci čtečka sahá až po okraj displeje s výjimkou horního okraje, který je umístěn pod spodním okraj navigační lišty aplikace.

Pokud tedy máte na mysli, že by měla aplikace při otevření detailu obrázku přejít do "fullscreenu", je to samozřejmě možné, ovšem implementačně závislé na cílové aplikaci a ne čtečce jako takové.

**Comment by Fiser33** [comment]
Po blizsim prezkoumani predpokladam, ze tato otazka se tykala zobrazeni aplikace na iPadech, kde aplikace nebyla zobrazena pres celou obrazovku, ale byla po stranach ohranicena cernymi bloky. 

Takoveto zobrazeni ovsem stale nebylo zpusobeno knihovnou, ovsem nastavenim testovaci aplikace. Nastaveni jsem opravil ve verzi 1.0 (4).

**Comment by zabak** [comment]
ano, testuju na ipadech. Vyřešeno, zavírám.
