### ISSUE TITLE
Při rychlém zmenšení se stránka rozpadne

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#7]
Pokud udělám zoom out tak abych na konci toho zoomu viděl celý obrázek, tak tam najednou probliknou dlaždice z (asi) maximálního zoomu. Pokud nechám prsty u sebe, tak tam ty dlaždice zůstanou dokud to nepustím.

![img_20161227_225330](https://cloud.githubusercontent.com/assets/811537/21509316/040846c0-cc88-11e6-914b-7768735cae72.jpg)

**Comment by Fiser33** [comment]
Opraveno v testovaci aplikaci verze 1.0 (6). Prosim o kontrolu.
