### ISSUE TITLE
Po "puštění" obrazovky při zoomování obraz přeblikne

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOSTiledViewer#9]
Předpokládám, že souvisí s #1 
Když zoomuju, tak dokud držím prsty na displeji, tak se obraz nepřekreslí, ale jak ho pustím, tak celý obraz problikne a překreslí se. Předpokládám, že to nastane v okamžiku, kdy se přechází na jinou úroveň dlaždic.

**Comment by zabak** [comment]
To bliknutí je tak rychlé, že nevidím, co tam vlastně problikává, ale myslím,ž e by tam to bliknutí nemuselo vůbec být.

**Comment by Fiser33** [comment]
fixed
